scrapper/urls.py
from django.urls import path
from scrapper import views
from .task import add

app_name = 'scrapper'

urlpatterns = [

    
    path("", views.webcrawl_input, name='search'),
    path('result/', add, name='result'),



]

webscrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrapper.urls', namespace='scrapper'))
]

scrapper/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Post(models.Model):
    Content_Type = models.CharField(max_length=255)
    Article_Title = models.CharField(max_length=255)
    Words_Per_Column = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'search done on {self.header} at {self.created}'

     

scrapper/forms.py
from django import forms
from .models import Post


class WebForm(forms.ModelForm):


    class Meta:
        model = Post
        fields = ('Content_Type', 'Article_Title', 'Words_Per_Column',)

scrapper/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
#from .models import Post
from .forms import WebForm
from .task import add



def webcrawl_input(request):
    
    task = False
    message = None
    if request.method == "GET":
        form = WebForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['Content_Type']}  and {cd['Article_Title']} and {cd['Words_Per_Column']}"
            request.session['url'] = cd['Content_Type']
            request.session['sub'] = cd['Article_Title']
            request.session['char'] = cd['Words_Per_Column']
            task = True
            
            #add.delay(request)
            # post = form.save(commit=False)
            # post.header = form['header']
            # post.sub_header =  form['sub_header']
            # post.character_len = form['character_len']
            # post.save()

    else:
        form = WebForm()

    return render(request,
                'post/detail.html', {'form': form, 'message': message, 'task':task})

scrapper/templates/post/detail.html
{% block content %} {% load bootstrap4 %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#register').click(function() {
            $(this).prop('disabled', true);
            $("#content").show();

            setTimeout(function() {
                $('#register').prop('disabled', false);
            }, 60000);

        });
    });

    function myFunction() {
        alert("Please wait while we fecth result");
    }
</script>






<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Checkout example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/checkout/">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
</head>

<body class="bg-light">
    <div class="container">
        <div class="py-5 text-center">
            <h2>Corpus Creation Portal</h2>
            <!-- <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p> -->
        </div>


        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>
            window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')
        </script>
        <script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="form-validation.js"></script> -->



        {% if task %}
        <div class="container-fluid" style="text-align:center;">
            <h3>Fetching Result </h3>
            <h3 class="lead">
                {{ message}} {{ result}} {{air_result}}
            </h3>
        </div>
        <div class="container-fluid">
            <h2 class="lead" id="list"> </h2>
        </div>
        <form>
            <div class="col-md-12 text-center">
                <button id="register" class="btn btn-primary" onclick="myFunction()">view data </button>
            </div>
        </form>
        </h3>
    </div>

    {% else%}

    <h2>Arcticle Parameters</h2>
    <form method="get" action="{% url 'scrapper:search' %}">{% csrf_token %} {% bootstrap_form form %} {% buttons %}
        <div class="container-fluid" style="text-align:center;">
            <button class="btn btn-primary" type="submit">
            Submit
            </button> {% endbuttons %}
        </div>
    </form>


    {% endif %} {% endblock %}

    <script>
        $(document).ready(function() {
            $('urbutton').attr('disabled', false);
        });
    </script>




    <script>
        let fetchBtn = document.getElementById("register");


        fetchBtn.addEventListener("click", buttonclickhandler);

        function buttonclickhandler() {
            var request = new XMLHttpRequest()

            request.open('GET', 'http://127.0.0.1:8000/result', true)
            request.onload = function() {
                // Begin accessing JSON data here
                var data = JSON.parse(this.response)

                if (request.status >= 200 && request.status < 400) {

                    // Getting the ul element
                    let list = document.getElementById("list");
                    str = ""

                    data.forEach(res => {
                        Object.entries(res).forEach(([key, value]) => {
                            str += `<p>${value}</p>`;
                        })
                    })
                    list.innerHTML = str;


                } else {
                    console.log('error')
                }
            }

            request.send()
        }
    </script>

</body>

</html>

scrapper/templates/post/detail2.html
{% block content %}

<h2>Fetching and Analyzing Text</h2>

{{message}} {{task}} {% endblock %}